sudo: required

services: docker

git:
  # we don't want travis to pull them for the lint build,
  # so we pull them manually in the tests build
  submodules: false

env:
  matrix:
    - LINT_CHECK="1"
    - TESTS="1"
  global:
    - DOCKER_COMPOSE_VERSION="1.7.1"
    - TESTS="0" LINT_CHECK="0"
    - ADDONS_DIR=${TRAVIS_BUILD_DIR}/odoo/local-src
    - SONGS_DIR=${TRAVIS_BUILD_DIR}/odoo/songs
    - COMPOSE_PROJECT_NAME=enfinfidu
    - RANCHER_STACK_NAME=enfinfidu-odoo-test
    - secure: "gwTwV6KFcUOVOY57xDI8kb4sMynpuBYXfkS4ZJExzlLhXG0nx1f6j06Ns9KGdHezlu7ZZZjAYwdNcJS8cMzIcE1niSmbF0JfoArqVbMegMFZegYoQzqefw3iLnUmI01MtWGbBeDbr0zm6v0Nc4w1MdfMS6spb4Z0CErP8p+dOup/2zEcDc8m180tIHcxR5x12d9EwjnlvL7/8eDhuXHh+yolZ2ca2z1Moucqoh49HsE78Bq2M639knHsq3r+c5NPur9XilpNsWD0qWq5hIfyPQPge9PEtpxIlYXR3/+MyQ4etjP8uEFw+ocfE1QMJMIbo3hAOSkGUKsuJIbG579URTEUDeM9hyqTri+ZKmgs+nPRSB63IkDOYZR7lfajVlEHAYnFP/zS4yyrVuTblY/YtMxFPsJDmpsjSM8Qb+jdH906p6BFXPlWojyzLPIAeVYC8yhxJgyeZzT3r5mlm8Ld+Y9IXfYyBnXoa8SwLmqNeyG0lbe3KM2fXHIBAU5RrTJLh0aB1JYOFoGYJvr7HgNrWmSE2w0NNOqaif6/V3oFA5rK4fms3q6AaMCqGXbU9qU6kV/6kZnW39ZXCavICluRtrse7zqd70KX9XC66OfF6KkwVVyFOTkh4zZW7oWTbCqBycPbKYqrxRCqSWBdVV4J5m0J/uYSBg4ibr73DArgz9o="

before_install:
  - sudo apt-get update
  - sudo DEBIAN_FRONTEND=noninteractive apt-get install -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" docker-engine --yes --force-yes
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - git config --global user.name "TravisCI"
  - git config --global user.email "travis@camptocamp.com"
  - if [ "$LINT_CHECK" == "1" ] ; then pip install --user -q flake8 ; fi
  - if [ "$LINT_CHECK" == "0" ] ; then pip install --user -q gitpython ; fi

install:
  - if [ "$LINT_CHECK" == "0" ] ; then python ./travis/git_submodule_update.py ; fi
    # we always specify '-f docker-compose.yml' so 'docker-compose.override.yml'
    # is not used and so the volumes are not shared with the host
  - if [ "$LINT_CHECK" == "0" ] ; then docker-compose -f docker-compose.yml build --pull ; fi
  - if [ "$TESTS" == "1" ] ; then docker-compose -f docker-compose.yml up -d db ; fi
  - if [ "$TESTS" == "1" ] ; then docker-compose -f docker-compose.yml ps ; fi

# We run the tests and scenario in the same build, so we can push the docker image
# after that we validated it has tests and scenario passing
script:
  - if [ "$LINT_CHECK" == "1" ] ; then flake8 ${ADDONS_DIR} ${SONGS_DIR} --exclude=__init__.py ; fi
  - if [ "$TESTS" == "1" ] ; then docker-compose -f docker-compose.yml run --rm -e ODOO_CLOUD_PLATFORM_UNSAFE=1 -e DEMO=True -e CI=True odoo runtests ; fi
  # run the scenario
  - if [ "$TESTS" == "1" ] ; then docker-compose -f docker-compose.yml run --rm -e ODOO_CLOUD_PLATFORM_UNSAFE=1 -e MARABUNTA_MODE=demo -e MARABUNTA_ALLOW_SERIE=True odoo odoo --stop-after-init ; fi

after_success:
  - if [ "$TESTS" == "1" ] ; then ./travis/publish.sh ; fi
